CARD_TYPE = (
    ('1', 'Monster'),
    ('2', 'Spell'),
    ('3', 'Trap'),
    ('4', 'Skill'),
    ('5', 'Token'),
    ('6', 'Other'),
)

CARD_SUBTYPE = (
    ('1', 'Effect Monster'),
    ('2', 'Flip Effect Monster'),
    ('3', 'Flip Tuner Effect Monster'),
    ('4', 'Gemini Monster'),
    ('5', 'Normal Monster'),
    ('6', 'Normal Tuner Monster'),
    ('7', 'Pendulum Effect Monster'),
    ('8', 'Pendulum Flip Effect Monster'),
    ('9', 'Pendulum Normal Monster'),
    ('10', 'Pendulum Tuner Effect Monster'),
    ('11', 'Ritual Effect Monster'),
    ('12', 'Ritual Monster'),
    ('13', 'Skill Card'),
    ('14', 'Spell Card'),
    ('15', 'Spirit Monster'),
    ('16', 'Toon Monster'),
    ('17', 'Trap Card'),
    ('18', 'Tuner Monster'),
    ('19', 'Union Effect Monster'),
    ('20', 'Fusion Monster'),
    ('21', 'Link Monster'),
    ('22', 'Pendulum Effect Fusion Monster'),
    ('23', 'Synchro Monster'),
    ('24', 'Synchro Pendulum Effect Monster'),
    ('25', 'Synchro Tuner Monster'),
    ('26', 'XYZ Monster'),
    ('27', 'XYZ Pendulum Effect Monster'),
    ('28', 'Token Card'),
    ('29', 'Pendulum Normal Tuner Monster'),

)

MONSTER_RACE = (
    ('1', 'Aqua'),
    ('2', 'Beast'),
    ('3', 'Beast-Warrior'),
    ('4', 'Creator-God'),
    ('5', 'Cyberse'),
    ('6', 'Dinosaur'),
    ('7', 'Divine-Beast'),
    ('8', 'Dragon'),
    ('9', 'Fairy'),
    ('10', 'Fiend'),
    ('11', 'Fish'),
    ('12', 'Insect'),
    ('13', 'Machine'),
    ('14', 'Plant'),
    ('15', 'Psychic'),
    ('16', 'Pyro'),
    ('17', 'Reptile'),
    ('18', 'Rock'),
    ('19', 'Sea Serpent'),
    ('20', 'Spellcaster'),
    ('21', 'Thunder'),
    ('22', 'Warrior'),
    ('23', 'Winged Beast'),
    ('24', 'Wyrm'),
    ('25', 'Zombie'),
)

MAGIC_TRAP_RACE = (
    ('1', 'Normal'),
    ('2', 'Field'),
    ('3', 'Equip'),
    ('4', 'Continuous'),
    ('5', 'Quick-Play'),
    ('6', 'Ritual'),
    ('7', 'Counter'),
)

CARD_ATTRIBUTE = (
    ('1', 'Dark'),
    ('2', 'Light'),
    ('3', 'Divine'),
    ('4', 'Earth'),
    ('5', 'Fire'),
    ('6', 'Water'),
    ('7', 'Wind'),
)

CARD_RARITY = (
    ('1', 'Common'),
    ('2', 'Rare'),
    ('3', 'Super rare'),
    ('4', 'Ultra rare'),
    ('5', 'Ultimate rare'),
    ('6', 'Secret rare'),
    ('7', 'Prismatic secret rare'),
    ('8', 'Ghost rare'),
    ('9', 'Parallel rarity'),
    ('10', 'Duel terminal'),
    ('11', 'Gold rare'),
    ('12', 'Premium gold rare'),
    ('13', 'Extra Secret Rare'),
    ('14', 'N/A'),
    ('15', 'Other'),
    ('16', 'Gold secret rare'),

)

LINK_MARKERS = (
    ('1', 'Top'),
    ('2', 'Bottom'),
    ('3', 'Left'),
    ('4', 'Right'),
    ('5', 'Bottom-Left'),
    ('6', 'Bottom-Right'),
    ('7', 'Top-Left'),
    ('8', 'Top-Right')
)
