-- Yu-Gi-Oh! Card Collection Manager - Database Schema
-- Generated by: python manage.py export_schema
-- This file contains only the database structure (tables, columns, indexes, constraints)
-- No data is included.

BEGIN;

CREATE TABLE IF NOT EXISTS "auth_group" (
    "id" integer NOT NULL DEFAULT nextval('auth_group_id_seq'::regclass),
    "name" character varying(150) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX auth_group_name_key ON public.auth_group USING btree (name);
CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);

CREATE TABLE IF NOT EXISTS "auth_group_permissions" (
    "id" bigint NOT NULL DEFAULT nextval('auth_group_permissions_id_seq'::regclass),
    "group_id" integer NOT NULL,
    "permission_id" integer NOT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX auth_group_permissions_group_id_permission_id_0cd325b0_uniq ON public.auth_group_permissions USING btree (group_id, permission_id);
CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);
CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_fk" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id");
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_permission_id_fk" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id");

CREATE TABLE IF NOT EXISTS "auth_permission" (
    "id" integer NOT NULL DEFAULT nextval('auth_permission_id_seq'::regclass),
    "name" character varying(255) NOT NULL,
    "content_type_id" integer NOT NULL,
    "codename" character varying(100) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX auth_permission_content_type_id_codename_01ab375a_uniq ON public.auth_permission USING btree (content_type_id, codename);
CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_fk" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id");

CREATE TABLE IF NOT EXISTS "auth_user" (
    "id" integer NOT NULL DEFAULT nextval('auth_user_id_seq'::regclass),
    "password" character varying(128) NOT NULL,
    "last_login" timestamp with time zone,
    "is_superuser" boolean NOT NULL,
    "username" character varying(150) NOT NULL,
    "first_name" character varying(150) NOT NULL,
    "last_name" character varying(150) NOT NULL,
    "email" character varying(254) NOT NULL,
    "is_staff" boolean NOT NULL,
    "is_active" boolean NOT NULL,
    "date_joined" timestamp with time zone NOT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX auth_user_username_key ON public.auth_user USING btree (username);
CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);

CREATE TABLE IF NOT EXISTS "auth_user_groups" (
    "id" bigint NOT NULL DEFAULT nextval('auth_user_groups_id_seq'::regclass),
    "user_id" integer NOT NULL,
    "group_id" integer NOT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX auth_user_groups_user_id_group_id_94350c0c_uniq ON public.auth_user_groups USING btree (user_id, group_id);
CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);
CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id");
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_group_id_fk" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id");

CREATE TABLE IF NOT EXISTS "auth_user_user_permissions" (
    "id" bigint NOT NULL DEFAULT nextval('auth_user_user_permissions_id_seq'::regclass),
    "user_id" integer NOT NULL,
    "permission_id" integer NOT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX auth_user_user_permissions_user_id_permission_id_14a6b632_uniq ON public.auth_user_user_permissions USING btree (user_id, permission_id);
CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);
CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id");
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_permission_id_fk" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id");

CREATE TABLE IF NOT EXISTS "card_attribute" (
    "id" integer NOT NULL DEFAULT nextval('card_attribute_id_seq'::regclass),
    "state" boolean NOT NULL,
    "created_date" date NOT NULL,
    "modified_date" date NOT NULL,
    "deleted_date" date NOT NULL,
    "name" character varying(50) NOT NULL,
    PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "card_card" (
    "id" integer NOT NULL DEFAULT nextval('card_card_id_seq'::regclass),
    "state" boolean NOT NULL,
    "created_date" date NOT NULL,
    "modified_date" date NOT NULL,
    "deleted_date" date NOT NULL,
    "serial_code" character varying(60) NOT NULL,
    "card_number" character varying(60) NOT NULL,
    "name" character varying(255) NOT NULL,
    "set_name" character varying(255),
    "edition" character varying(80) NOT NULL,
    "amount" integer NOT NULL,
    "img_code" character varying(20),
    "rarity_id" integer,
    "subtype_id" integer,
    "type_id" integer,
    "note" character varying(255),
    "format" character varying(255),
    "banned" character varying(255),
    "language" character varying(255) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX card_card_serial_code_key ON public.card_card USING btree (serial_code);
CREATE INDEX card_card_serial_code_3db926da_like ON public.card_card USING btree (serial_code varchar_pattern_ops);
CREATE INDEX card_card_rarity_id_56dfe8fe ON public.card_card USING btree (rarity_id);
CREATE INDEX card_card_subtype_id_6a88ffe4 ON public.card_card USING btree (subtype_id);
CREATE INDEX card_card_type_id_e7a96266 ON public.card_card USING btree (type_id);
CREATE INDEX card_card_card_number_6c2e8574 ON public.card_card USING btree (card_number);
CREATE INDEX card_card_card_number_6c2e8574_like ON public.card_card USING btree (card_number varchar_pattern_ops);
CREATE INDEX card_card_name_e171d36c ON public.card_card USING btree (name);
CREATE INDEX card_card_name_e171d36c_like ON public.card_card USING btree (name varchar_pattern_ops);
ALTER TABLE "card_card" ADD CONSTRAINT "card_card_rarity_id_fk" FOREIGN KEY ("rarity_id") REFERENCES "card_rarity" ("id");
ALTER TABLE "card_card" ADD CONSTRAINT "card_card_subtype_id_fk" FOREIGN KEY ("subtype_id") REFERENCES "card_subtype" ("id");
ALTER TABLE "card_card" ADD CONSTRAINT "card_card_type_id_fk" FOREIGN KEY ("type_id") REFERENCES "card_type" ("id");

CREATE TABLE IF NOT EXISTS "card_generalmonster" (
    "monster_ptr_id" integer NOT NULL,
    "defence" character varying(20) NOT NULL,
    "level" character varying(20),
    PRIMARY KEY ("monster_ptr_id")
);

ALTER TABLE "card_generalmonster" ADD CONSTRAINT "card_generalmonster_monster_ptr_id_fk" FOREIGN KEY ("monster_ptr_id") REFERENCES "card_monster" ("card_ptr_id");

CREATE TABLE IF NOT EXISTS "card_historicalattribute" (
    "id" integer NOT NULL,
    "state" boolean NOT NULL,
    "created_date" date NOT NULL,
    "modified_date" date NOT NULL,
    "deleted_date" date NOT NULL,
    "name" character varying(50) NOT NULL,
    "history_id" integer NOT NULL DEFAULT nextval('card_historicalattribute_history_id_seq'::regclass),
    "history_date" timestamp with time zone NOT NULL,
    "history_change_reason" character varying(100),
    "history_type" character varying(1) NOT NULL,
    "history_user_id" integer,
    PRIMARY KEY ("history_id")
);

CREATE INDEX card_historicalattribute_id_5a3beb19 ON public.card_historicalattribute USING btree (id);
CREATE INDEX card_historicalattribute_history_user_id_c208737d ON public.card_historicalattribute USING btree (history_user_id);
CREATE INDEX card_historicalattribute_history_date_fca5c970 ON public.card_historicalattribute USING btree (history_date);
ALTER TABLE "card_historicalattribute" ADD CONSTRAINT "card_historicalattribute_history_user_id_fk" FOREIGN KEY ("history_user_id") REFERENCES "auth_user" ("id");

CREATE TABLE IF NOT EXISTS "card_historicalcard" (
    "id" integer NOT NULL,
    "state" boolean NOT NULL,
    "created_date" date NOT NULL,
    "modified_date" date NOT NULL,
    "deleted_date" date NOT NULL,
    "serial_code" character varying(60) NOT NULL,
    "card_number" character varying(60) NOT NULL,
    "name" character varying(255) NOT NULL,
    "set_name" character varying(255),
    "edition" character varying(80) NOT NULL,
    "amount" integer NOT NULL,
    "img_code" character varying(20),
    "history_id" integer NOT NULL DEFAULT nextval('card_historicalcard_history_id_seq'::regclass),
    "history_date" timestamp with time zone NOT NULL,
    "history_change_reason" character varying(100),
    "history_type" character varying(1) NOT NULL,
    "history_user_id" integer,
    "rarity_id" integer,
    "subtype_id" integer,
    "type_id" integer,
    "note" character varying(255),
    "format" character varying(255),
    "banned" character varying(255),
    "language" character varying(255) NOT NULL,
    PRIMARY KEY ("history_id")
);

CREATE INDEX card_historicalcard_id_c16a1485 ON public.card_historicalcard USING btree (id);
CREATE INDEX card_historicalcard_serial_code_57a4021f ON public.card_historicalcard USING btree (serial_code);
CREATE INDEX card_historicalcard_serial_code_57a4021f_like ON public.card_historicalcard USING btree (serial_code varchar_pattern_ops);
CREATE INDEX card_historicalcard_history_user_id_d96a7e1e ON public.card_historicalcard USING btree (history_user_id);
CREATE INDEX card_historicalcard_rarity_id_2d056150 ON public.card_historicalcard USING btree (rarity_id);
CREATE INDEX card_historicalcard_subtype_id_353fc36e ON public.card_historicalcard USING btree (subtype_id);
CREATE INDEX card_historicalcard_type_id_093099f0 ON public.card_historicalcard USING btree (type_id);
CREATE INDEX card_historicalcard_card_number_2241b7aa ON public.card_historicalcard USING btree (card_number);
CREATE INDEX card_historicalcard_card_number_2241b7aa_like ON public.card_historicalcard USING btree (card_number varchar_pattern_ops);
CREATE INDEX card_historicalcard_history_date_09bb781e ON public.card_historicalcard USING btree (history_date);
CREATE INDEX card_historicalcard_name_8c51e67e ON public.card_historicalcard USING btree (name);
CREATE INDEX card_historicalcard_name_8c51e67e_like ON public.card_historicalcard USING btree (name varchar_pattern_ops);
ALTER TABLE "card_historicalcard" ADD CONSTRAINT "card_historicalcard_history_user_id_fk" FOREIGN KEY ("history_user_id") REFERENCES "auth_user" ("id");

CREATE TABLE IF NOT EXISTS "card_historicalgeneralmonster" (
    "card_ptr_id" integer,
    "monster_ptr_id" integer,
    "id" integer NOT NULL,
    "state" boolean NOT NULL,
    "created_date" date NOT NULL,
    "modified_date" date NOT NULL,
    "deleted_date" date NOT NULL,
    "serial_code" character varying(60) NOT NULL,
    "card_number" character varying(60) NOT NULL,
    "name" character varying(255) NOT NULL,
    "set_name" character varying(255),
    "edition" character varying(80) NOT NULL,
    "amount" integer NOT NULL,
    "img_code" character varying(20),
    "description" character varying(2000) NOT NULL,
    "attack" character varying(20) NOT NULL,
    "archetype" character varying(250),
    "defence" character varying(20) NOT NULL,
    "level" character varying(20),
    "history_id" integer NOT NULL DEFAULT nextval('card_historicalgeneralmonster_history_id_seq'::regclass),
    "history_date" timestamp with time zone NOT NULL,
    "history_change_reason" character varying(100),
    "history_type" character varying(1) NOT NULL,
    "attribute_id" integer,
    "history_user_id" integer,
    "race_id" integer,
    "rarity_id" integer,
    "subtype_id" integer,
    "type_id" integer,
    "note" character varying(255),
    "format" character varying(255),
    "banned" character varying(255),
    "language" character varying(255) NOT NULL,
    PRIMARY KEY ("history_id")
);

CREATE INDEX card_historicalgeneralmonster_card_ptr_id_3e1d4fda ON public.card_historicalgeneralmonster USING btree (card_ptr_id);
CREATE INDEX card_historicalgeneralmonster_monster_ptr_id_e1ece127 ON public.card_historicalgeneralmonster USING btree (monster_ptr_id);
CREATE INDEX card_historicalgeneralmonster_id_e132634f ON public.card_historicalgeneralmonster USING btree (id);
CREATE INDEX card_historicalgeneralmonster_serial_code_38883fe0 ON public.card_historicalgeneralmonster USING btree (serial_code);
CREATE INDEX card_historicalgeneralmonster_serial_code_38883fe0_like ON public.card_historicalgeneralmonster USING btree (serial_code varchar_pattern_ops);
CREATE INDEX card_historicalgeneralmonster_attribute_id_846d762f ON public.card_historicalgeneralmonster USING btree (attribute_id);
CREATE INDEX card_historicalgeneralmonster_history_user_id_4d2b30d4 ON public.card_historicalgeneralmonster USING btree (history_user_id);
CREATE INDEX card_historicalgeneralmonster_race_id_f981009e ON public.card_historicalgeneralmonster USING btree (race_id);
CREATE INDEX card_historicalgeneralmonster_rarity_id_dde314b4 ON public.card_historicalgeneralmonster USING btree (rarity_id);
CREATE INDEX card_historicalgeneralmonster_subtype_id_d18941f4 ON public.card_historicalgeneralmonster USING btree (subtype_id);
CREATE INDEX card_historicalgeneralmonster_type_id_8163559f ON public.card_historicalgeneralmonster USING btree (type_id);
CREATE INDEX card_historicalgeneralmonster_card_number_2162443b ON public.card_historicalgeneralmonster USING btree (card_number);
CREATE INDEX card_historicalgeneralmonster_card_number_2162443b_like ON public.card_historicalgeneralmonster USING btree (card_number varchar_pattern_ops);
CREATE INDEX card_historicalgeneralmonster_history_date_de4d4861 ON public.card_historicalgeneralmonster USING btree (history_date);
CREATE INDEX card_historicalgeneralmonster_name_5bbab25a ON public.card_historicalgeneralmonster USING btree (name);
CREATE INDEX card_historicalgeneralmonster_name_5bbab25a_like ON public.card_historicalgeneralmonster USING btree (name varchar_pattern_ops);
ALTER TABLE "card_historicalgeneralmonster" ADD CONSTRAINT "card_historicalgeneralmonster_history_user_id_fk" FOREIGN KEY ("history_user_id") REFERENCES "auth_user" ("id");

CREATE TABLE IF NOT EXISTS "card_historicallinkmarker" (
    "id" integer NOT NULL,
    "state" boolean NOT NULL,
    "created_date" date NOT NULL,
    "modified_date" date NOT NULL,
    "deleted_date" date NOT NULL,
    "name" character varying(50) NOT NULL,
    "history_id" integer NOT NULL DEFAULT nextval('card_historicallinkmarker_history_id_seq'::regclass),
    "history_date" timestamp with time zone NOT NULL,
    "history_change_reason" character varying(100),
    "history_type" character varying(1) NOT NULL,
    "history_user_id" integer,
    PRIMARY KEY ("history_id")
);

CREATE INDEX card_historicallinkmarker_id_1dc79c6a ON public.card_historicallinkmarker USING btree (id);
CREATE INDEX card_historicallinkmarker_history_user_id_f385b104 ON public.card_historicallinkmarker USING btree (history_user_id);
CREATE INDEX card_historicallinkmarker_history_date_1cef9871 ON public.card_historicallinkmarker USING btree (history_date);
ALTER TABLE "card_historicallinkmarker" ADD CONSTRAINT "card_historicallinkmarker_history_user_id_fk" FOREIGN KEY ("history_user_id") REFERENCES "auth_user" ("id");

CREATE TABLE IF NOT EXISTS "card_historicallinkmonster" (
    "card_ptr_id" integer,
    "monster_ptr_id" integer,
    "id" integer NOT NULL,
    "state" boolean NOT NULL,
    "created_date" date NOT NULL,
    "modified_date" date NOT NULL,
    "deleted_date" date NOT NULL,
    "serial_code" character varying(60) NOT NULL,
    "card_number" character varying(60) NOT NULL,
    "name" character varying(255) NOT NULL,
    "set_name" character varying(255),
    "edition" character varying(80) NOT NULL,
    "amount" integer NOT NULL,
    "img_code" character varying(20),
    "description" character varying(2000) NOT NULL,
    "attack" character varying(20) NOT NULL,
    "archetype" character varying(250),
    "link_value" integer NOT NULL,
    "history_id" integer NOT NULL DEFAULT nextval('card_historicallinkmonster_history_id_seq'::regclass),
    "history_date" timestamp with time zone NOT NULL,
    "history_change_reason" character varying(100),
    "history_type" character varying(1) NOT NULL,
    "attribute_id" integer,
    "history_user_id" integer,
    "race_id" integer,
    "rarity_id" integer,
    "subtype_id" integer,
    "type_id" integer,
    "note" character varying(255),
    "format" character varying(255),
    "banned" character varying(255),
    "language" character varying(255) NOT NULL,
    PRIMARY KEY ("history_id")
);

CREATE INDEX card_historicallinkmonster_card_ptr_id_9d79e726 ON public.card_historicallinkmonster USING btree (card_ptr_id);
CREATE INDEX card_historicallinkmonster_monster_ptr_id_238a0c5d ON public.card_historicallinkmonster USING btree (monster_ptr_id);
CREATE INDEX card_historicallinkmonster_id_b33b3d42 ON public.card_historicallinkmonster USING btree (id);
CREATE INDEX card_historicallinkmonster_serial_code_07eeda0c ON public.card_historicallinkmonster USING btree (serial_code);
CREATE INDEX card_historicallinkmonster_serial_code_07eeda0c_like ON public.card_historicallinkmonster USING btree (serial_code varchar_pattern_ops);
CREATE INDEX card_historicallinkmonster_attribute_id_5f514cde ON public.card_historicallinkmonster USING btree (attribute_id);
CREATE INDEX card_historicallinkmonster_history_user_id_f827ebe5 ON public.card_historicallinkmonster USING btree (history_user_id);
CREATE INDEX card_historicallinkmonster_race_id_7bc1d17f ON public.card_historicallinkmonster USING btree (race_id);
CREATE INDEX card_historicallinkmonster_rarity_id_906b1034 ON public.card_historicallinkmonster USING btree (rarity_id);
CREATE INDEX card_historicallinkmonster_subtype_id_7733a692 ON public.card_historicallinkmonster USING btree (subtype_id);
CREATE INDEX card_historicallinkmonster_type_id_7d316f92 ON public.card_historicallinkmonster USING btree (type_id);
CREATE INDEX card_historicallinkmonster_card_number_251384fd ON public.card_historicallinkmonster USING btree (card_number);
CREATE INDEX card_historicallinkmonster_card_number_251384fd_like ON public.card_historicallinkmonster USING btree (card_number varchar_pattern_ops);
CREATE INDEX card_historicallinkmonster_history_date_8a425c8e ON public.card_historicallinkmonster USING btree (history_date);
CREATE INDEX card_historicallinkmonster_name_59b8c0a5 ON public.card_historicallinkmonster USING btree (name);
CREATE INDEX card_historicallinkmonster_name_59b8c0a5_like ON public.card_historicallinkmonster USING btree (name varchar_pattern_ops);
ALTER TABLE "card_historicallinkmonster" ADD CONSTRAINT "card_historicallinkmonster_history_user_id_fk" FOREIGN KEY ("history_user_id") REFERENCES "auth_user" ("id");

CREATE TABLE IF NOT EXISTS "card_historicalmagictrapcard" (
    "card_ptr_id" integer,
    "id" integer NOT NULL,
    "state" boolean NOT NULL,
    "created_date" date NOT NULL,
    "modified_date" date NOT NULL,
    "deleted_date" date NOT NULL,
    "serial_code" character varying(60) NOT NULL,
    "card_number" character varying(60) NOT NULL,
    "name" character varying(255) NOT NULL,
    "set_name" character varying(255),
    "edition" character varying(80) NOT NULL,
    "amount" integer NOT NULL,
    "img_code" character varying(20),
    "description" character varying(1000) NOT NULL,
    "history_id" integer NOT NULL DEFAULT nextval('card_historicalmagictrapcard_history_id_seq'::regclass),
    "history_date" timestamp with time zone NOT NULL,
    "history_change_reason" character varying(100),
    "history_type" character varying(1) NOT NULL,
    "history_user_id" integer,
    "race_id" integer,
    "rarity_id" integer,
    "subtype_id" integer,
    "type_id" integer,
    "archetype" character varying(250),
    "note" character varying(255),
    "format" character varying(255),
    "banned" character varying(255),
    "language" character varying(255) NOT NULL,
    PRIMARY KEY ("history_id")
);

CREATE INDEX card_historicalmagictrapcard_card_ptr_id_86ec6076 ON public.card_historicalmagictrapcard USING btree (card_ptr_id);
CREATE INDEX card_historicalmagictrapcard_id_e69af3c0 ON public.card_historicalmagictrapcard USING btree (id);
CREATE INDEX card_historicalmagictrapcard_serial_code_9efcabca ON public.card_historicalmagictrapcard USING btree (serial_code);
CREATE INDEX card_historicalmagictrapcard_serial_code_9efcabca_like ON public.card_historicalmagictrapcard USING btree (serial_code varchar_pattern_ops);
CREATE INDEX card_historicalmagictrapcard_history_user_id_c836d236 ON public.card_historicalmagictrapcard USING btree (history_user_id);
CREATE INDEX card_historicalmagictrapcard_race_id_c71b8855 ON public.card_historicalmagictrapcard USING btree (race_id);
CREATE INDEX card_historicalmagictrapcard_rarity_id_a0d52c0a ON public.card_historicalmagictrapcard USING btree (rarity_id);
CREATE INDEX card_historicalmagictrapcard_subtype_id_e0515e19 ON public.card_historicalmagictrapcard USING btree (subtype_id);
CREATE INDEX card_historicalmagictrapcard_type_id_ae2efd30 ON public.card_historicalmagictrapcard USING btree (type_id);
CREATE INDEX card_historicalmagictrapcard_card_number_f437b4a6 ON public.card_historicalmagictrapcard USING btree (card_number);
CREATE INDEX card_historicalmagictrapcard_card_number_f437b4a6_like ON public.card_historicalmagictrapcard USING btree (card_number varchar_pattern_ops);
CREATE INDEX card_historicalmagictrapcard_history_date_ff40d581 ON public.card_historicalmagictrapcard USING btree (history_date);
CREATE INDEX card_historicalmagictrapcard_name_6ce22c57 ON public.card_historicalmagictrapcard USING btree (name);
CREATE INDEX card_historicalmagictrapcard_name_6ce22c57_like ON public.card_historicalmagictrapcard USING btree (name varchar_pattern_ops);
ALTER TABLE "card_historicalmagictrapcard" ADD CONSTRAINT "card_historicalmagictrapcard_history_user_id_fk" FOREIGN KEY ("history_user_id") REFERENCES "auth_user" ("id");

CREATE TABLE IF NOT EXISTS "card_historicalmagictraprace" (
    "id" integer NOT NULL,
    "state" boolean NOT NULL,
    "created_date" date NOT NULL,
    "modified_date" date NOT NULL,
    "deleted_date" date NOT NULL,
    "name" character varying(50) NOT NULL,
    "history_id" integer NOT NULL DEFAULT nextval('card_historicalmagictraprace_history_id_seq'::regclass),
    "history_date" timestamp with time zone NOT NULL,
    "history_change_reason" character varying(100),
    "history_type" character varying(1) NOT NULL,
    "history_user_id" integer,
    PRIMARY KEY ("history_id")
);

CREATE INDEX card_historicalmagictraprace_id_e7c1fd2a ON public.card_historicalmagictraprace USING btree (id);
CREATE INDEX card_historicalmagictraprace_history_user_id_23c4063c ON public.card_historicalmagictraprace USING btree (history_user_id);
CREATE INDEX card_historicalmagictraprace_history_date_df611d0d ON public.card_historicalmagictraprace USING btree (history_date);
ALTER TABLE "card_historicalmagictraprace" ADD CONSTRAINT "card_historicalmagictraprace_history_user_id_fk" FOREIGN KEY ("history_user_id") REFERENCES "auth_user" ("id");

CREATE TABLE IF NOT EXISTS "card_historicalmonster" (
    "card_ptr_id" integer,
    "id" integer NOT NULL,
    "state" boolean NOT NULL,
    "created_date" date NOT NULL,
    "modified_date" date NOT NULL,
    "deleted_date" date NOT NULL,
    "serial_code" character varying(60) NOT NULL,
    "card_number" character varying(60) NOT NULL,
    "name" character varying(255) NOT NULL,
    "set_name" character varying(255),
    "edition" character varying(80) NOT NULL,
    "amount" integer NOT NULL,
    "img_code" character varying(20),
    "description" character varying(2000) NOT NULL,
    "attack" character varying(20) NOT NULL,
    "archetype" character varying(250),
    "history_id" integer NOT NULL DEFAULT nextval('card_historicalmonster_history_id_seq'::regclass),
    "history_date" timestamp with time zone NOT NULL,
    "history_change_reason" character varying(100),
    "history_type" character varying(1) NOT NULL,
    "attribute_id" integer,
    "history_user_id" integer,
    "race_id" integer,
    "rarity_id" integer,
    "subtype_id" integer,
    "type_id" integer,
    "note" character varying(255),
    "format" character varying(255),
    "banned" character varying(255),
    "language" character varying(255) NOT NULL,
    PRIMARY KEY ("history_id")
);

CREATE INDEX card_historicalmonster_card_ptr_id_dbbc3bf9 ON public.card_historicalmonster USING btree (card_ptr_id);
CREATE INDEX card_historicalmonster_id_72f2416c ON public.card_historicalmonster USING btree (id);
CREATE INDEX card_historicalmonster_serial_code_db81ddd0 ON public.card_historicalmonster USING btree (serial_code);
CREATE INDEX card_historicalmonster_serial_code_db81ddd0_like ON public.card_historicalmonster USING btree (serial_code varchar_pattern_ops);
CREATE INDEX card_historicalmonster_attribute_id_c8a42e10 ON public.card_historicalmonster USING btree (attribute_id);
CREATE INDEX card_historicalmonster_history_user_id_8e4de643 ON public.card_historicalmonster USING btree (history_user_id);
CREATE INDEX card_historicalmonster_race_id_62f9e209 ON public.card_historicalmonster USING btree (race_id);
CREATE INDEX card_historicalmonster_rarity_id_c66221d0 ON public.card_historicalmonster USING btree (rarity_id);
CREATE INDEX card_historicalmonster_subtype_id_d0331ec7 ON public.card_historicalmonster USING btree (subtype_id);
CREATE INDEX card_historicalmonster_type_id_1a693af8 ON public.card_historicalmonster USING btree (type_id);
CREATE INDEX card_historicalmonster_card_number_f537bc38 ON public.card_historicalmonster USING btree (card_number);
CREATE INDEX card_historicalmonster_card_number_f537bc38_like ON public.card_historicalmonster USING btree (card_number varchar_pattern_ops);
CREATE INDEX card_historicalmonster_history_date_7796eb66 ON public.card_historicalmonster USING btree (history_date);
CREATE INDEX card_historicalmonster_name_de4d02ca ON public.card_historicalmonster USING btree (name);
CREATE INDEX card_historicalmonster_name_de4d02ca_like ON public.card_historicalmonster USING btree (name varchar_pattern_ops);
ALTER TABLE "card_historicalmonster" ADD CONSTRAINT "card_historicalmonster_history_user_id_fk" FOREIGN KEY ("history_user_id") REFERENCES "auth_user" ("id");

CREATE TABLE IF NOT EXISTS "card_historicalpendulummonster" (
    "card_ptr_id" integer,
    "monster_ptr_id" integer,
    "id" integer NOT NULL,
    "state" boolean NOT NULL,
    "created_date" date NOT NULL,
    "modified_date" date NOT NULL,
    "deleted_date" date NOT NULL,
    "serial_code" character varying(60) NOT NULL,
    "card_number" character varying(60) NOT NULL,
    "name" character varying(255) NOT NULL,
    "set_name" character varying(255),
    "edition" character varying(80) NOT NULL,
    "amount" integer NOT NULL,
    "img_code" character varying(20),
    "description" character varying(2000) NOT NULL,
    "attack" character varying(20) NOT NULL,
    "archetype" character varying(250),
    "scale" integer NOT NULL,
    "defence" character varying(20) NOT NULL,
    "level" character varying(20),
    "history_id" integer NOT NULL DEFAULT nextval('card_historicalpendulummonster_history_id_seq'::regclass),
    "history_date" timestamp with time zone NOT NULL,
    "history_change_reason" character varying(100),
    "history_type" character varying(1) NOT NULL,
    "attribute_id" integer,
    "history_user_id" integer,
    "race_id" integer,
    "rarity_id" integer,
    "subtype_id" integer,
    "type_id" integer,
    "note" character varying(255),
    "format" character varying(255),
    "banned" character varying(255),
    "language" character varying(255) NOT NULL,
    PRIMARY KEY ("history_id")
);

CREATE INDEX card_historicalpendulummonster_card_ptr_id_50ad99f8 ON public.card_historicalpendulummonster USING btree (card_ptr_id);
CREATE INDEX card_historicalpendulummonster_monster_ptr_id_86f8cd6a ON public.card_historicalpendulummonster USING btree (monster_ptr_id);
CREATE INDEX card_historicalpendulummonster_id_92733ca0 ON public.card_historicalpendulummonster USING btree (id);
CREATE INDEX card_historicalpendulummonster_serial_code_a60e0fde ON public.card_historicalpendulummonster USING btree (serial_code);
CREATE INDEX card_historicalpendulummonster_serial_code_a60e0fde_like ON public.card_historicalpendulummonster USING btree (serial_code varchar_pattern_ops);
CREATE INDEX card_historicalpendulummonster_attribute_id_17ca9218 ON public.card_historicalpendulummonster USING btree (attribute_id);
CREATE INDEX card_historicalpendulummonster_history_user_id_69eab7c4 ON public.card_historicalpendulummonster USING btree (history_user_id);
CREATE INDEX card_historicalpendulummonster_race_id_09c7b98e ON public.card_historicalpendulummonster USING btree (race_id);
CREATE INDEX card_historicalpendulummonster_rarity_id_55562aa4 ON public.card_historicalpendulummonster USING btree (rarity_id);
CREATE INDEX card_historicalpendulummonster_subtype_id_1ea8f6e0 ON public.card_historicalpendulummonster USING btree (subtype_id);
CREATE INDEX card_historicalpendulummonster_type_id_697aa1da ON public.card_historicalpendulummonster USING btree (type_id);
CREATE INDEX card_historicalpendulummonster_card_number_3370eaed ON public.card_historicalpendulummonster USING btree (card_number);
CREATE INDEX card_historicalpendulummonster_card_number_3370eaed_like ON public.card_historicalpendulummonster USING btree (card_number varchar_pattern_ops);
CREATE INDEX card_historicalpendulummonster_history_date_42d71f00 ON public.card_historicalpendulummonster USING btree (history_date);
CREATE INDEX card_historicalpendulummonster_name_264db482 ON public.card_historicalpendulummonster USING btree (name);
CREATE INDEX card_historicalpendulummonster_name_264db482_like ON public.card_historicalpendulummonster USING btree (name varchar_pattern_ops);
ALTER TABLE "card_historicalpendulummonster" ADD CONSTRAINT "card_historicalpendulummonster_history_user_id_fk" FOREIGN KEY ("history_user_id") REFERENCES "auth_user" ("id");

CREATE TABLE IF NOT EXISTS "card_historicalrace" (
    "id" integer NOT NULL,
    "state" boolean NOT NULL,
    "created_date" date NOT NULL,
    "modified_date" date NOT NULL,
    "deleted_date" date NOT NULL,
    "name" character varying(50) NOT NULL,
    "history_id" integer NOT NULL DEFAULT nextval('card_historicalrace_history_id_seq'::regclass),
    "history_date" timestamp with time zone NOT NULL,
    "history_change_reason" character varying(100),
    "history_type" character varying(1) NOT NULL,
    "history_user_id" integer,
    PRIMARY KEY ("history_id")
);

CREATE INDEX card_historicalrace_id_e53b8425 ON public.card_historicalrace USING btree (id);
CREATE INDEX card_historicalrace_history_user_id_d1428984 ON public.card_historicalrace USING btree (history_user_id);
CREATE INDEX card_historicalrace_history_date_0b278862 ON public.card_historicalrace USING btree (history_date);
ALTER TABLE "card_historicalrace" ADD CONSTRAINT "card_historicalrace_history_user_id_fk" FOREIGN KEY ("history_user_id") REFERENCES "auth_user" ("id");

CREATE TABLE IF NOT EXISTS "card_historicalrarity" (
    "id" integer NOT NULL,
    "state" boolean NOT NULL,
    "created_date" date NOT NULL,
    "modified_date" date NOT NULL,
    "deleted_date" date NOT NULL,
    "name" character varying(50) NOT NULL,
    "history_id" integer NOT NULL DEFAULT nextval('card_historicalrarity_history_id_seq'::regclass),
    "history_date" timestamp with time zone NOT NULL,
    "history_change_reason" character varying(100),
    "history_type" character varying(1) NOT NULL,
    "history_user_id" integer,
    PRIMARY KEY ("history_id")
);

CREATE INDEX card_historicalrarity_id_8739f907 ON public.card_historicalrarity USING btree (id);
CREATE INDEX card_historicalrarity_history_user_id_e2195ae2 ON public.card_historicalrarity USING btree (history_user_id);
CREATE INDEX card_historicalrarity_history_date_a6001a07 ON public.card_historicalrarity USING btree (history_date);
ALTER TABLE "card_historicalrarity" ADD CONSTRAINT "card_historicalrarity_history_user_id_fk" FOREIGN KEY ("history_user_id") REFERENCES "auth_user" ("id");

CREATE TABLE IF NOT EXISTS "card_historicalskillcard" (
    "card_ptr_id" integer,
    "id" integer NOT NULL,
    "state" boolean NOT NULL,
    "created_date" date NOT NULL,
    "modified_date" date NOT NULL,
    "deleted_date" date NOT NULL,
    "serial_code" character varying(60) NOT NULL,
    "card_number" character varying(60) NOT NULL,
    "name" character varying(255) NOT NULL,
    "set_name" character varying(255),
    "edition" character varying(80) NOT NULL,
    "amount" integer NOT NULL,
    "img_code" character varying(20),
    "description" character varying(1000) NOT NULL,
    "race" character varying(250) NOT NULL,
    "history_id" integer NOT NULL DEFAULT nextval('card_historicalskillcard_history_id_seq'::regclass),
    "history_date" timestamp with time zone NOT NULL,
    "history_change_reason" character varying(100),
    "history_type" character varying(1) NOT NULL,
    "history_user_id" integer,
    "rarity_id" integer,
    "subtype_id" integer,
    "type_id" integer,
    "note" character varying(255),
    "format" character varying(255),
    "banned" character varying(255),
    "language" character varying(255) NOT NULL,
    PRIMARY KEY ("history_id")
);

CREATE INDEX card_historicalskillcard_card_ptr_id_1928945b ON public.card_historicalskillcard USING btree (card_ptr_id);
CREATE INDEX card_historicalskillcard_id_1133ba6c ON public.card_historicalskillcard USING btree (id);
CREATE INDEX card_historicalskillcard_serial_code_b97a266d ON public.card_historicalskillcard USING btree (serial_code);
CREATE INDEX card_historicalskillcard_serial_code_b97a266d_like ON public.card_historicalskillcard USING btree (serial_code varchar_pattern_ops);
CREATE INDEX card_historicalskillcard_history_user_id_14aa1914 ON public.card_historicalskillcard USING btree (history_user_id);
CREATE INDEX card_historicalskillcard_rarity_id_7f4a4fb9 ON public.card_historicalskillcard USING btree (rarity_id);
CREATE INDEX card_historicalskillcard_subtype_id_d6a9d2da ON public.card_historicalskillcard USING btree (subtype_id);
CREATE INDEX card_historicalskillcard_type_id_128b8391 ON public.card_historicalskillcard USING btree (type_id);
CREATE INDEX card_historicalskillcard_card_number_8e46e7b4 ON public.card_historicalskillcard USING btree (card_number);
CREATE INDEX card_historicalskillcard_card_number_8e46e7b4_like ON public.card_historicalskillcard USING btree (card_number varchar_pattern_ops);
CREATE INDEX card_historicalskillcard_history_date_df5d065d ON public.card_historicalskillcard USING btree (history_date);
CREATE INDEX card_historicalskillcard_name_4e520744 ON public.card_historicalskillcard USING btree (name);
CREATE INDEX card_historicalskillcard_name_4e520744_like ON public.card_historicalskillcard USING btree (name varchar_pattern_ops);
ALTER TABLE "card_historicalskillcard" ADD CONSTRAINT "card_historicalskillcard_history_user_id_fk" FOREIGN KEY ("history_user_id") REFERENCES "auth_user" ("id");

CREATE TABLE IF NOT EXISTS "card_historicalsubtype" (
    "id" integer NOT NULL,
    "state" boolean NOT NULL,
    "created_date" date NOT NULL,
    "modified_date" date NOT NULL,
    "deleted_date" date NOT NULL,
    "name" character varying(50) NOT NULL,
    "history_id" integer NOT NULL DEFAULT nextval('card_historicalsubtype_history_id_seq'::regclass),
    "history_date" timestamp with time zone NOT NULL,
    "history_change_reason" character varying(100),
    "history_type" character varying(1) NOT NULL,
    "history_user_id" integer,
    PRIMARY KEY ("history_id")
);

CREATE INDEX card_historicalsubtype_id_4cdc7594 ON public.card_historicalsubtype USING btree (id);
CREATE INDEX card_historicalsubtype_history_user_id_37d7f2e9 ON public.card_historicalsubtype USING btree (history_user_id);
CREATE INDEX card_historicalsubtype_history_date_bfce34d1 ON public.card_historicalsubtype USING btree (history_date);
ALTER TABLE "card_historicalsubtype" ADD CONSTRAINT "card_historicalsubtype_history_user_id_fk" FOREIGN KEY ("history_user_id") REFERENCES "auth_user" ("id");

CREATE TABLE IF NOT EXISTS "card_historicaltype" (
    "id" integer NOT NULL,
    "state" boolean NOT NULL,
    "created_date" date NOT NULL,
    "modified_date" date NOT NULL,
    "deleted_date" date NOT NULL,
    "name" character varying(50) NOT NULL,
    "history_id" integer NOT NULL DEFAULT nextval('card_historicaltype_history_id_seq'::regclass),
    "history_date" timestamp with time zone NOT NULL,
    "history_change_reason" character varying(100),
    "history_type" character varying(1) NOT NULL,
    "history_user_id" integer,
    PRIMARY KEY ("history_id")
);

CREATE INDEX card_historicaltype_id_5a132b90 ON public.card_historicaltype USING btree (id);
CREATE INDEX card_historicaltype_history_user_id_92ff9d0b ON public.card_historicaltype USING btree (history_user_id);
CREATE INDEX card_historicaltype_history_date_1e47e611 ON public.card_historicaltype USING btree (history_date);
ALTER TABLE "card_historicaltype" ADD CONSTRAINT "card_historicaltype_history_user_id_fk" FOREIGN KEY ("history_user_id") REFERENCES "auth_user" ("id");

CREATE TABLE IF NOT EXISTS "card_linkmarker" (
    "id" integer NOT NULL DEFAULT nextval('card_linkmarker_id_seq'::regclass),
    "state" boolean NOT NULL,
    "created_date" date NOT NULL,
    "modified_date" date NOT NULL,
    "deleted_date" date NOT NULL,
    "name" character varying(50) NOT NULL,
    PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "card_linkmonster" (
    "monster_ptr_id" integer NOT NULL,
    "link_value" integer NOT NULL,
    PRIMARY KEY ("monster_ptr_id")
);

ALTER TABLE "card_linkmonster" ADD CONSTRAINT "card_linkmonster_monster_ptr_id_fk" FOREIGN KEY ("monster_ptr_id") REFERENCES "card_monster" ("card_ptr_id");

CREATE TABLE IF NOT EXISTS "card_linkmonster_link_markers" (
    "id" bigint NOT NULL DEFAULT nextval('card_linkmonster_link_markers_id_seq'::regclass),
    "linkmonster_id" integer NOT NULL,
    "linkmarker_id" integer NOT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX card_linkmonster_link_ma_linkmonster_id_linkmarke_7979e81c_uniq ON public.card_linkmonster_link_markers USING btree (linkmonster_id, linkmarker_id);
CREATE INDEX card_linkmonster_link_markers_linkmonster_id_eaaeca39 ON public.card_linkmonster_link_markers USING btree (linkmonster_id);
CREATE INDEX card_linkmonster_link_markers_linkmarker_id_f18328d7 ON public.card_linkmonster_link_markers USING btree (linkmarker_id);
ALTER TABLE "card_linkmonster_link_markers" ADD CONSTRAINT "card_linkmonster_link_markers_linkmonster_id_fk" FOREIGN KEY ("linkmonster_id") REFERENCES "card_linkmonster" ("monster_ptr_id");
ALTER TABLE "card_linkmonster_link_markers" ADD CONSTRAINT "card_linkmonster_link_markers_linkmarker_id_fk" FOREIGN KEY ("linkmarker_id") REFERENCES "card_linkmarker" ("id");

CREATE TABLE IF NOT EXISTS "card_magictrapcard" (
    "card_ptr_id" integer NOT NULL,
    "description" character varying(1000) NOT NULL,
    "race_id" integer NOT NULL,
    "archetype" character varying(250),
    PRIMARY KEY ("card_ptr_id")
);

CREATE INDEX card_magictrapcard_race_id_43109149 ON public.card_magictrapcard USING btree (race_id);
ALTER TABLE "card_magictrapcard" ADD CONSTRAINT "card_magictrapcard_card_ptr_id_fk" FOREIGN KEY ("card_ptr_id") REFERENCES "card_card" ("id");
ALTER TABLE "card_magictrapcard" ADD CONSTRAINT "card_magictrapcard_race_id_fk" FOREIGN KEY ("race_id") REFERENCES "card_magictraprace" ("id");

CREATE TABLE IF NOT EXISTS "card_magictraprace" (
    "id" integer NOT NULL DEFAULT nextval('card_magictraprace_id_seq'::regclass),
    "state" boolean NOT NULL,
    "created_date" date NOT NULL,
    "modified_date" date NOT NULL,
    "deleted_date" date NOT NULL,
    "name" character varying(50) NOT NULL,
    PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "card_monster" (
    "card_ptr_id" integer NOT NULL,
    "description" character varying(2000) NOT NULL,
    "attack" character varying(20) NOT NULL,
    "archetype" character varying(250),
    "attribute_id" integer,
    "race_id" integer,
    PRIMARY KEY ("card_ptr_id")
);

CREATE INDEX card_monster_attribute_id_e98f65d8 ON public.card_monster USING btree (attribute_id);
CREATE INDEX card_monster_race_id_66ece913 ON public.card_monster USING btree (race_id);
ALTER TABLE "card_monster" ADD CONSTRAINT "card_monster_card_ptr_id_fk" FOREIGN KEY ("card_ptr_id") REFERENCES "card_card" ("id");
ALTER TABLE "card_monster" ADD CONSTRAINT "card_monster_attribute_id_fk" FOREIGN KEY ("attribute_id") REFERENCES "card_attribute" ("id");
ALTER TABLE "card_monster" ADD CONSTRAINT "card_monster_race_id_fk" FOREIGN KEY ("race_id") REFERENCES "card_race" ("id");

CREATE TABLE IF NOT EXISTS "card_pendulummonster" (
    "monster_ptr_id" integer NOT NULL,
    "scale" integer NOT NULL,
    "defence" character varying(20) NOT NULL,
    "level" character varying(20),
    PRIMARY KEY ("monster_ptr_id")
);

ALTER TABLE "card_pendulummonster" ADD CONSTRAINT "card_pendulummonster_monster_ptr_id_fk" FOREIGN KEY ("monster_ptr_id") REFERENCES "card_monster" ("card_ptr_id");

CREATE TABLE IF NOT EXISTS "card_race" (
    "id" integer NOT NULL DEFAULT nextval('card_race_id_seq'::regclass),
    "state" boolean NOT NULL,
    "created_date" date NOT NULL,
    "modified_date" date NOT NULL,
    "deleted_date" date NOT NULL,
    "name" character varying(50) NOT NULL,
    PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "card_rarity" (
    "id" integer NOT NULL DEFAULT nextval('card_rarity_id_seq'::regclass),
    "state" boolean NOT NULL,
    "created_date" date NOT NULL,
    "modified_date" date NOT NULL,
    "deleted_date" date NOT NULL,
    "name" character varying(50) NOT NULL,
    PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "card_skillcard" (
    "card_ptr_id" integer NOT NULL,
    "description" character varying(1000) NOT NULL,
    "race" character varying(250) NOT NULL,
    PRIMARY KEY ("card_ptr_id")
);

ALTER TABLE "card_skillcard" ADD CONSTRAINT "card_skillcard_card_ptr_id_fk" FOREIGN KEY ("card_ptr_id") REFERENCES "card_card" ("id");

CREATE TABLE IF NOT EXISTS "card_subtype" (
    "id" integer NOT NULL DEFAULT nextval('card_subtype_id_seq'::regclass),
    "state" boolean NOT NULL,
    "created_date" date NOT NULL,
    "modified_date" date NOT NULL,
    "deleted_date" date NOT NULL,
    "name" character varying(50) NOT NULL,
    PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "card_type" (
    "id" integer NOT NULL DEFAULT nextval('card_type_id_seq'::regclass),
    "state" boolean NOT NULL,
    "created_date" date NOT NULL,
    "modified_date" date NOT NULL,
    "deleted_date" date NOT NULL,
    "name" character varying(50) NOT NULL,
    PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "django_admin_log" (
    "id" integer NOT NULL DEFAULT nextval('django_admin_log_id_seq'::regclass),
    "action_time" timestamp with time zone NOT NULL,
    "object_id" text,
    "object_repr" character varying(200) NOT NULL,
    "action_flag" smallint NOT NULL,
    "change_message" text NOT NULL,
    "content_type_id" integer,
    "user_id" integer NOT NULL,
    PRIMARY KEY ("id")
);

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);
CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_fk" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id");
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id");

CREATE TABLE IF NOT EXISTS "django_content_type" (
    "id" integer NOT NULL DEFAULT nextval('django_content_type_id_seq'::regclass),
    "app_label" character varying(100) NOT NULL,
    "model" character varying(100) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX django_content_type_app_label_model_76bd3d3b_uniq ON public.django_content_type USING btree (app_label, model);

CREATE TABLE IF NOT EXISTS "django_migrations" (
    "id" bigint NOT NULL DEFAULT nextval('django_migrations_id_seq'::regclass),
    "app" character varying(255) NOT NULL,
    "name" character varying(255) NOT NULL,
    "applied" timestamp with time zone NOT NULL,
    PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "django_session" (
    "session_key" character varying(40) NOT NULL,
    "session_data" text NOT NULL,
    "expire_date" timestamp with time zone NOT NULL,
    PRIMARY KEY ("session_key")
);

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);
CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);

COMMIT;