# Generated by Django 4.0.4 on 2022-05-02 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_skillcard_alter_card_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rarity', to='card.rarity'),
        ),
    ]
