# Generated by Django 4.0.4 on 2022-05-02 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_alter_card_subtype_alter_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='card.attribute'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monster_race', to='card.race'),
        ),
    ]
