# Generated by Django 4.0.4 on 2022-05-28 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_alter_historicalsubtype_name_alter_subtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rarity', to='card.rarity'),
        ),
    ]
