# Generated by Django 4.0.4 on 2022-06-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0014_card_note_historicalcard_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='format',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Format'),
        ),
        migrations.AddField(
            model_name='historicalcard',
            name='format',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Format'),
        ),
        migrations.AddField(
            model_name='historicalgeneralmonster',
            name='format',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Format'),
        ),
        migrations.AddField(
            model_name='historicallinkmonster',
            name='format',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Format'),
        ),
        migrations.AddField(
            model_name='historicalmagictrapcard',
            name='format',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Format'),
        ),
        migrations.AddField(
            model_name='historicalmonster',
            name='format',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Format'),
        ),
        migrations.AddField(
            model_name='historicalpendulummonster',
            name='format',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Format'),
        ),
        migrations.AddField(
            model_name='historicalskillcard',
            name='format',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Format'),
        ),
    ]
