# Generated by Django 4.0.4 on 2022-06-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0015_card_format_historicalcard_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='banned',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banned'),
        ),
        migrations.AddField(
            model_name='historicalcard',
            name='banned',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banned'),
        ),
        migrations.AddField(
            model_name='historicalgeneralmonster',
            name='banned',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banned'),
        ),
        migrations.AddField(
            model_name='historicallinkmonster',
            name='banned',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banned'),
        ),
        migrations.AddField(
            model_name='historicalmagictrapcard',
            name='banned',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banned'),
        ),
        migrations.AddField(
            model_name='historicalmonster',
            name='banned',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banned'),
        ),
        migrations.AddField(
            model_name='historicalpendulummonster',
            name='banned',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banned'),
        ),
        migrations.AddField(
            model_name='historicalskillcard',
            name='banned',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banned'),
        ),
    ]
