# Generated by Django 4.0.4 on 2022-06-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0017_alter_historicalrarity_name_alter_rarity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalgeneralmonster',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicallinkmonster',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalmonster',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalpendulummonster',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='Description'),
        ),
    ]
