# Generated by Django 4.0.4 on 2022-04-16 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmagictrapcard',
            name='race',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='card.magictraprace'),
        ),
        migrations.AlterField(
            model_name='magictrapcard',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_trap_race', to='card.magictraprace'),
        ),
    ]
