# Generated by Django 4.0.4 on 2022-04-30 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card', '0003_historicalmagictrapcard_archetype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card.card')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('race', models.CharField(max_length=250, verbose_name='Race')),
            ],
            options={
                'verbose_name': 'Skill Card',
                'verbose_name_plural': 'Skill Cards',
            },
            bases=('card.card',),
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['card_number', 'serial_code'], 'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
        migrations.AlterField(
            model_name='historicaltype',
            name='name',
            field=models.CharField(choices=[('1', 'Monster'), ('2', 'Spell'), ('3', 'Trap'), ('4', 'Skill'), ('5', 'Token')], max_length=50),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('1', 'Monster'), ('2', 'Spell'), ('3', 'Trap'), ('4', 'Skill'), ('5', 'Token')], max_length=50),
        ),
        migrations.CreateModel(
            name='HistoricalSkillCard',
            fields=[
                ('card_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='card.card')),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Status')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Created Date')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Updated Date')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Deleted Date')),
                ('serial_code', models.CharField(db_index=True, max_length=60, verbose_name='Serial Code')),
                ('card_number', models.CharField(max_length=60, verbose_name='Card Number')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('set_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Set Name')),
                ('edition', models.CharField(blank=True, default='', max_length=80, verbose_name='Edition')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('img_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Image Code')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('race', models.CharField(max_length=250, verbose_name='Race')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rarity', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='card.rarity')),
                ('subtype', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='card.subtype')),
                ('type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='card.type')),
            ],
            options={
                'verbose_name': 'historical Skill Card',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
