# Generated by Django 4.0.4 on 2022-05-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_alter_monster_attribute_alter_monster_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalgeneralmonster',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicallinkmonster',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalmonster',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalpendulummonster',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Description'),
        ),
    ]
