# Generated by Django 4.0.4 on 2022-06-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_alter_card_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='historicalcard',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='historicalgeneralmonster',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='historicallinkmonster',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='historicalmagictrapcard',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='historicalmonster',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='historicalpendulummonster',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='historicalskillcard',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='historicalrace',
            name='name',
            field=models.CharField(choices=[('1', 'Aqua'), ('2', 'Beast'), ('3', 'Beast-Warrior'), ('4', 'Creator-God'), ('5', 'Cyberse'), ('6', 'Dinosaur'), ('7', 'Divine-Beast'), ('8', 'Dragon'), ('9', 'Fairy'), ('10', 'Fiend'), ('11', 'Fish'), ('12', 'Insect'), ('13', 'Machine'), ('14', 'Plant'), ('15', 'Psychic'), ('16', 'Pyro'), ('17', 'Reptile'), ('18', 'Rock'), ('19', 'Sea Serpent'), ('20', 'Spellcaster'), ('21', 'Thunder'), ('22', 'Warrior'), ('23', 'Winged Beast'), ('24', 'Wyrm'), ('25', 'Zombie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalrarity',
            name='name',
            field=models.CharField(choices=[('1', 'Common'), ('2', 'Rare'), ('3', 'Super rare'), ('4', 'Ultra rare'), ('5', 'Ultimate rare'), ('6', 'Secret rare'), ('7', 'Prismatic secret rare'), ('8', 'Ghost rare'), ('9', 'Parallel rarity'), ('10', 'Duel terminal'), ('11', 'Gold rare'), ('12', 'Premium gold rare'), ('13', 'Extra Secret Rare'), ('14', 'N/A'), ('15', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaltype',
            name='name',
            field=models.CharField(choices=[('1', 'Monster'), ('2', 'Spell'), ('3', 'Trap'), ('4', 'Skill'), ('5', 'Token'), ('6', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(choices=[('1', 'Aqua'), ('2', 'Beast'), ('3', 'Beast-Warrior'), ('4', 'Creator-God'), ('5', 'Cyberse'), ('6', 'Dinosaur'), ('7', 'Divine-Beast'), ('8', 'Dragon'), ('9', 'Fairy'), ('10', 'Fiend'), ('11', 'Fish'), ('12', 'Insect'), ('13', 'Machine'), ('14', 'Plant'), ('15', 'Psychic'), ('16', 'Pyro'), ('17', 'Reptile'), ('18', 'Rock'), ('19', 'Sea Serpent'), ('20', 'Spellcaster'), ('21', 'Thunder'), ('22', 'Warrior'), ('23', 'Winged Beast'), ('24', 'Wyrm'), ('25', 'Zombie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rarity',
            name='name',
            field=models.CharField(choices=[('1', 'Common'), ('2', 'Rare'), ('3', 'Super rare'), ('4', 'Ultra rare'), ('5', 'Ultimate rare'), ('6', 'Secret rare'), ('7', 'Prismatic secret rare'), ('8', 'Ghost rare'), ('9', 'Parallel rarity'), ('10', 'Duel terminal'), ('11', 'Gold rare'), ('12', 'Premium gold rare'), ('13', 'Extra Secret Rare'), ('14', 'N/A'), ('15', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('1', 'Monster'), ('2', 'Spell'), ('3', 'Trap'), ('4', 'Skill'), ('5', 'Token'), ('6', 'Other')], max_length=50),
        ),
    ]
