# Generated by Django 4.2.30 on 2026-07-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0019_card_language_historicalcard_language_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalattribute',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Attribute', 'verbose_name_plural': 'historical Attributes'},
        ),
        migrations.AlterModelOptions(
            name='historicalcard',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Card', 'verbose_name_plural': 'historical Cards'},
        ),
        migrations.AlterModelOptions(
            name='historicalgeneralmonster',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical General Monster', 'verbose_name_plural': 'historical General Monster'},
        ),
        migrations.AlterModelOptions(
            name='historicallinkmarker',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Link Marker', 'verbose_name_plural': 'historical Link Markers'},
        ),
        migrations.AlterModelOptions(
            name='historicallinkmonster',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Link Monster', 'verbose_name_plural': 'historical Link Monsters'},
        ),
        migrations.AlterModelOptions(
            name='historicalmagictrapcard',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Magic/Trap Card', 'verbose_name_plural': 'historical Magic/Trap Cards'},
        ),
        migrations.AlterModelOptions(
            name='historicalmagictraprace',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Magic/Trap Race', 'verbose_name_plural': 'historical Magic/Trap Races'},
        ),
        migrations.AlterModelOptions(
            name='historicalmonster',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Monster', 'verbose_name_plural': 'historical Monsters'},
        ),
        migrations.AlterModelOptions(
            name='historicalpendulummonster',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Pendulum Monster', 'verbose_name_plural': 'historical Pendulum Monsters'},
        ),
        migrations.AlterModelOptions(
            name='historicalrace',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Race', 'verbose_name_plural': 'historical Races'},
        ),
        migrations.AlterModelOptions(
            name='historicalrarity',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Rarity', 'verbose_name_plural': 'historical Rarities'},
        ),
        migrations.AlterModelOptions(
            name='historicalskillcard',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Skill Card', 'verbose_name_plural': 'historical Skill Cards'},
        ),
        migrations.AlterModelOptions(
            name='historicalsubtype',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Subtype', 'verbose_name_plural': 'historical Subtypes'},
        ),
        migrations.AlterModelOptions(
            name='historicaltype',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Type', 'verbose_name_plural': 'historical Types'},
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(db_index=True, max_length=60, verbose_name='Card Number'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalattribute',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcard',
            name='card_number',
            field=models.CharField(db_index=True, max_length=60, verbose_name='Card Number'),
        ),
        migrations.AlterField(
            model_name='historicalcard',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcard',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalgeneralmonster',
            name='card_number',
            field=models.CharField(db_index=True, max_length=60, verbose_name='Card Number'),
        ),
        migrations.AlterField(
            model_name='historicalgeneralmonster',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalgeneralmonster',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicallinkmarker',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicallinkmonster',
            name='card_number',
            field=models.CharField(db_index=True, max_length=60, verbose_name='Card Number'),
        ),
        migrations.AlterField(
            model_name='historicallinkmonster',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicallinkmonster',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalmagictrapcard',
            name='card_number',
            field=models.CharField(db_index=True, max_length=60, verbose_name='Card Number'),
        ),
        migrations.AlterField(
            model_name='historicalmagictrapcard',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmagictrapcard',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalmagictraprace',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmonster',
            name='card_number',
            field=models.CharField(db_index=True, max_length=60, verbose_name='Card Number'),
        ),
        migrations.AlterField(
            model_name='historicalmonster',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmonster',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalpendulummonster',
            name='card_number',
            field=models.CharField(db_index=True, max_length=60, verbose_name='Card Number'),
        ),
        migrations.AlterField(
            model_name='historicalpendulummonster',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpendulummonster',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalrace',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalrarity',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalskillcard',
            name='card_number',
            field=models.CharField(db_index=True, max_length=60, verbose_name='Card Number'),
        ),
        migrations.AlterField(
            model_name='historicalskillcard',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalskillcard',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalsubtype',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltype',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
