"""
Django management command to export the database schema as SQL (structure only, no data).
Usage: python manage.py export_schema
"""
import os
from django.core.management.base import BaseCommand
from django.db import connection


class Command(BaseCommand):
    help = 'Export database schema as SQL (structure only, no data)'

    def handle(self, *args, **options):
        tables = connection.introspection.table_names()
        schema_sql = []

        schema_sql.append('-- Yu-Gi-Oh! Card Collection Manager - Database Schema')
        schema_sql.append('-- Generated by: python manage.py export_schema')
        schema_sql.append('-- This file contains only the database structure (tables, columns, indexes, constraints)')
        schema_sql.append('-- No data is included.')
        schema_sql.append('')
        schema_sql.append('BEGIN;')
        schema_sql.append('')

        for table_name in sorted(tables):
            # Get table definition via pg_get_tabledef
            with connection.cursor() as cursor:
                # Get columns
                cursor.execute("""
                    SELECT
                        a.attname AS column_name,
                        pg_catalog.format_type(a.atttypid, a.atttypmod) AS data_type,
                        a.attnotnull AS not_null,
                        COALESCE(pg_get_expr(d.adbin, d.adrelid), '') AS default_value
                    FROM pg_attribute a
                    LEFT JOIN pg_attrdef d ON (a.attrelid, a.attnum) = (d.adrelid, d.adnum)
                    WHERE a.attrelid = %s::regclass
                    AND a.attnum > 0
                    AND NOT a.attisdropped
                    ORDER BY a.attnum
                """, [table_name])
                columns = cursor.fetchall()

                # Get primary key
                cursor.execute("""
                    SELECT a.attname
                    FROM pg_index i
                    JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
                    WHERE i.indrelid = %s::regclass AND i.indisprimary
                """, [table_name])
                pk_cols = [row[0] for row in cursor.fetchall()]

                # Get indexes
                cursor.execute("""
                    SELECT indexname, indexdef
                    FROM pg_indexes
                    WHERE tablename = %s
                """, [table_name])
                indexes = cursor.fetchall()

                # Get foreign keys
                cursor.execute("""
                    SELECT
                        kcu.column_name,
                        ccu.table_name AS foreign_table,
                        ccu.column_name AS foreign_column
                    FROM information_schema.table_constraints tc
                    JOIN information_schema.key_column_usage kcu ON tc.constraint_name = kcu.constraint_name
                    JOIN information_schema.constraint_column_usage ccu ON ccu.constraint_name = tc.constraint_name
                    WHERE tc.table_name = %s AND tc.constraint_type = 'FOREIGN KEY'
                """, [table_name])
                foreign_keys = cursor.fetchall()

            # Build CREATE TABLE
            schema_sql.append(f'CREATE TABLE IF NOT EXISTS "{table_name}" (')
            col_lines = []
            for col in columns:
                col_name, data_type, not_null, default_val = col
                line = f'    "{col_name}" {data_type}'
                if not_null:
                    line += ' NOT NULL'
                if default_val:
                    line += f' DEFAULT {default_val}'
                col_lines.append(line)

            if pk_cols:
                pk_list = ", ".join('"' + c + '"' for c in pk_cols)
                col_lines.append('    PRIMARY KEY (' + pk_list + ')')

            schema_sql.append(',\n'.join(col_lines))
            schema_sql.append(');')
            schema_sql.append('')

            # Add indexes (skip primary key index)
            for idx in indexes:
                idx_name, idx_def = idx
                if 'pkey' not in idx_name:
                    schema_sql.append(idx_def + ';')

            # Add foreign keys
            for fk in foreign_keys:
                col_name, foreign_table, foreign_column = fk
                constraint_name = f'{table_name}_{col_name}_fk'
                schema_sql.append(
                    f'ALTER TABLE "{table_name}" '
                    f'ADD CONSTRAINT "{constraint_name}" '
                    f'FOREIGN KEY ("{col_name}") '
                    f'REFERENCES "{foreign_table}" ("{foreign_column}");'
                )

            schema_sql.append('')

        schema_sql.append('COMMIT;')

        output = '\n'.join(schema_sql)

        # Write to file (project root / db / schema.sql)
        from django.conf import settings
        project_root = os.path.dirname(os.path.dirname(settings.BASE_DIR))
        output_dir = os.path.join(project_root, 'db')
        os.makedirs(output_dir, exist_ok=True)
        output_path = os.path.join(output_dir, 'schema.sql')
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(output)

        self.stdout.write(self.style.SUCCESS(f'Schema exported to {output_path}'))
